{
 "title": "example websocket upbit",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "received ticker count",
   "type": "graph",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(received_ticker_total[$__rate_interval])"
    }
   ]
  },
  {
   "title": "received bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(received_size_bytes_sum[1m])"
    }
   ]
  },
  {
   "title": "connection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "connection_total" },
    { "expr": "disconnection_total" }
   ]
  }
 ]
}